ENT.Type = "anim"
ENT.Base = "base_entity"
ENT.PrintName = "Sniper Rounds"
ENT.Author = "Battlepope"
ENT.Spawnable = true
ENT.AdminSpawnable = true 
ENT.Category = "Hl2 Beta Ammo"
ENT.AmmoType = "bp_sniper"
ENT.Amount = 6